language: php
php:
    - 5.4
    - 5.5
    - 5.6
    - 7.0
    - hhvm

install:
    - composer self-update
    - composer --prefer-source install

script:
    - find src -type f -name "*.php" -exec php -l {} \;
